server:
  port: 7176

spring:
  datasource:
    url: jdbc:h2:mem:flightdb;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true          # 开发时可访问 http://localhost:8080/h2-console
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop  # 启动时自动建表，重启后清空（开发用）
    show-sql: false
    properties:
      hibernate:
        format_sql: true

# 跨域：允许前端 localhost:5173 访问
cors:
  allowed-origins: http://localhost:7175
